Repository PeriodPals/periodpals, pull requests merged in 2024-10, with the labels that each got.

#61 fix/authentication/signup : Fix authentication for CI-built APK
  app/src/main/AndroidManifest.xml
Labels: bug

#68 Fix/alert/UI tests: Fix and complete UI tests for AlertScreen
  app/build.gradle.kts
  app/src/androidTest/java/com/android/periodpals/ui/alert/AlertScreenTest.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertScreen.kt
  gradle/libs.versions.toml
Labels: bug

#91 Fix/navigation/top app bar UI tests
  app/src/androidTest/java/com/android/periodpals/ui/navigation/TopAppBarTest.kt
  app/src/main/java/com/android/periodpals/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
Labels: bug, enhancement

#96 fix/authentication/signup-ui-tests : Fix UI tests for M1: SignUp
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
Labels: bug

#88 feat/authentication/cleanup : Clean up code from M1: `model.auth` package
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/auth/AuthModel.kt
  app/src/main/java/com/android/periodpals/model/auth/PluginManagerWrapper.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModel.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationViewModel.kt
  app/src/main/java/com/android/periodpals/model/authentication/PluginManagerWrapper.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationViewModelTest.kt
Labels: documentation, clean up
