Repository PeriodPals/periodpals, pull requests merged in 2024-11, with the labels that each got.

#107 Misc/sonarcloud setup
  .github/workflows/ci.yml
  sonar-project.properties
Labels: bug

#113 ci: setup branch that build
  .github/workflows/AndroidBuild.yml
Labels: enhancement

#121 Fix/style/layout responsiveness/set up
  app/build.gradle.kts
  app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
  app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt
  app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
  app/src/main/java/com/android/periodpals/ui/theme/Theme.kt
  app/src/main/java/com/android/periodpals/ui/theme/Type.kt
  app/src/main/res/font/nunito_sans_black.ttf
  app/src/main/res/font/nunito_sans_black_italic.ttf
  app/src/main/res/font/nunito_sans_bold.ttf
  app/src/main/res/font/nunito_sans_bold_italic.ttf
  app/src/main/res/font/nunito_sans_extra_bold.ttf
  app/src/main/res/font/nunito_sans_extra_bold_italic.ttf
  app/src/main/res/font/nunito_sans_extra_light.ttf
  app/src/main/res/font/nunito_sans_extra_light_italic.ttf
  app/src/main/res/font/nunito_sans_italic.ttf
  app/src/main/res/font/nunito_sans_light.ttf
  app/src/main/res/font/nunito_sans_light_italic.ttf
  app/src/main/res/font/nunito_sans_regular.ttf
  app/src/main/res/font/nunito_sans_semi_bold.ttf
  app/src/main/res/font/nunito_sans_semi_bold_italic.ttf
Labels: enhancement

#131 Misc/sonarcloud-setup: fix sonarCloud report
  .github/workflows/ci.yml
  app/build.gradle.kts
  sonar-project.properties
Labels: bug

#135 Feat/authentication/AuthUserData
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModel.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationViewModel.kt
  app/src/main/java/com/android/periodpals/model/user/AuthUserData.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationViewModelTest.kt
Labels: enhancement

#110 Fix/geolocation/integrate location service
  app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/ui/map/Map.kt
Labels: bug, clean up

#100 feat/profile/cleanup : Clean up code from M1: `model.user`package
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModel.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationViewModel.kt
  app/src/main/java/com/android/periodpals/model/user/AuthenticationUserData.kt
  app/src/main/java/com/android/periodpals/model/user/UserAuthState.kt
  app/src/main/java/com/android/periodpals/model/user/UserAuthenticationState.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationViewModelTest.kt
Labels: documentation, clean up

#108 Feat/profile/edit profile screen UI and tests
  app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
Labels: enhancement

#125 feat/authentication/cleanup : Clean up code from M1 : `ui.authentication` package
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/main/java/com/android/periodpals/ui/components/AuthComponents.kt
  app/src/main/java/com/android/periodpals/ui/components/AuthenticationComponents.kt
Labels: documentation, clean up

#165 Feat/profile/fit screens to figma
  app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
Labels: enhancement

#162 feat/profile/integrate-vm-profile : Integrate profile VM into Profile screen
  app/src/androidTest/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
Labels: enhancement

#168 Feat/profile/shared components
  app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
Labels: enhancement

#170 Fix/style/layout responsivness/create profile
  app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/components/AuthenticationComponents.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/main/java/com/android/periodpals/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
  app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
  app/src/main/java/com/android/periodpals/ui/theme/Type.kt
Labels: enhancement

#171 build/authentication/fix-ci-build-apk : Fix secrets not properly applied in CI build apk
  .github/workflows/AndroidBuild.yml
  .github/workflows/ci.yml
  .gitignore
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  secrets.defaults.properties
Labels: enhancement

#167 Feat/alert/simple location dropdown
  app/build.gradle.kts
  app/src/androidTest/java/com/android/periodpals/ui/alert/CreateAlertScreenTest.kt
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/location/Location.kt
  app/src/main/java/com/android/periodpals/model/location/LocationModel.kt
  app/src/main/java/com/android/periodpals/model/location/LocationModelNominatim.kt
  app/src/main/java/com/android/periodpals/model/location/LocationViewModel.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/test/java/com/android/periodpals/model/location/LocationViewModelTest.kt
  app/src/test/java/com/android/periodpals/model/location/NominatimLocationRepositoryTest.kt
Labels: enhancement, help wanted

#183 feat: add "Current Location" as a selectable option.
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
Labels: enhancement

#173 Fix/style/layout responsivness/alert lists
  app/src/androidTest/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
  app/src/main/java/com/android/periodpals/ui/theme/Type.kt
Labels: enhancement

#185 Fix/style/layout responsivness/clean up
  app/src/androidTest/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/alert/CreateAlertScreenTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/main/java/com/android/periodpals/ui/components/AuthenticationComponents.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/main/java/com/android/periodpals/ui/map/Map.kt
  app/src/main/java/com/android/periodpals/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/periodpals/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
  app/src/main/java/com/android/periodpals/ui/timer/Timer.kt
Labels: enhancement

#189 Fix/authentication/sync-problems : Fix sync problem with auth screens
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationViewModel.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
Labels: bug

#196 Fix location fetching issue
  app/src/main/java/com/android/periodpals/model/location/LocationModelNominatim.kt
Labels: bug

#194 Fix/style/adapt light and dark mode
  app/src/main/java/com/android/periodpals/resources/Color.kt
  app/src/main/java/com/android/periodpals/resources/Dimens.kt
  app/src/main/java/com/android/periodpals/resources/Type.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/main/java/com/android/periodpals/ui/components/AuthenticationComponents.kt
  app/src/main/java/com/android/periodpals/ui/components/ErrorComponent.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/main/java/com/android/periodpals/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/periodpals/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt
  app/src/main/java/com/android/periodpals/ui/theme/Color.kt
  app/src/main/java/com/android/periodpals/ui/theme/Theme.kt
Labels: enhancement

#191 Fix/profile/sync-problems : Fix sync problem with CreateProfile screen
  app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/test/java/com/android/periodpals/model/user/UserModelSupabaseTest.kt
Labels: bug

#202 Updating architecture diagram for M2
  README.md
  architecture_diagram.excalidraw
Labels: documentation

#199 Test/misc/end-to-end-m1 : End-to-end tests for SignIn and SignUp flows
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndM1.kt
Labels: enhancement

#208 Feat/misc/robolectric : Add Robolectric to project
  app/build.gradle.kts
  app/src/androidTest/java/com/android/periodpals/MainActivityTest.kt
  app/src/androidTest/java/com/android/periodpals/screen/MainScreen.kt
  app/src/test/java/com/android/periodpals/ExampleUnitTest.kt
  app/src/test/java/com/android/periodpals/MainActivityTest.kt
  app/src/test/java/com/android/periodpals/PointTest.kt
  app/src/test/java/com/android/periodpals/navigation/NavigationActionsTest.kt
  app/src/test/java/com/android/periodpals/screen/SecondScreen.kt
  app/src/test/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/CreateAlertScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  app/src/test/java/com/android/periodpals/ui/map/MapScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/navigation/BottomNavigationMenuTest.kt
  app/src/test/java/com/android/periodpals/ui/navigation/TopAppBarTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
  app/src/test/resources/robolectric.properties
Labels: enhancement

#214 fix/misc/fix-e2e : Add tests to e2e branch
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndM1.kt
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndM2.kt
Labels: bug, documentation

#215 fix/misc/remove-e2e-from-main : Remove e2e from `main` branch
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndM1.kt
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndM2.kt
Labels: enhancement

#213 Feat/profile/implement delete account function
  app/src/main/java/com/android/periodpals/model/shared/SharedData.kt
  app/src/main/java/com/android/periodpals/model/user/UserModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt
  app/src/test/java/com/android/periodpals/model/user/UserModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
Labels: enhancement

#236 test/misc/fix-e2e-handle-push-perm-request : Fix end-to-end to handle push notification permission request dialog
  .github/workflows/ci.yml
  .gitignore
  app/.gitignore
  app/build.gradle.kts
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndM1.kt
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndM2.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/alert/Alert.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertDto.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertModel.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/main/java/com/android/periodpals/model/shared/SharedData.kt
  app/src/main/java/com/android/periodpals/model/user/UserModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/resources/Color.kt
  app/src/main/java/com/android/periodpals/resources/Dimens.kt
  app/src/main/java/com/android/periodpals/services/PushNotificationsService.kt
  app/src/main/java/com/android/periodpals/services/PushNotificationsServiceImpl.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/main/java/com/android/periodpals/ui/alert/EditAlert.kt
  app/src/main/java/com/android/periodpals/ui/components/AlertComponents.kt
  app/src/main/java/com/android/periodpals/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/periodpals/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/main/java/com/android/periodpals/ui/settings/SettingsScreen.kt
  app/src/main/java/com/android/periodpals/ui/timer/Timer.kt
  app/src/main/res/drawable/cotton.xml
  app/src/main/res/drawable/pad.xml
  app/src/main/res/drawable/tampon.xml
  app/src/main/res/drawable/tampon_and_pad.xml
  app/src/main/res/drawable/urgency_1.xml
  app/src/main/res/drawable/urgency_2.xml
  app/src/main/res/drawable/urgency_3.xml
  app/src/test/java/com/android/periodpals/model/alert/AlertModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertViewModelTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/periodpals/services/PushNotificationsServiceImplTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/CreateAlertScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/EditAlertScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/map/MapScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/navigation/TopAppBarTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/settings/SettingsScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: bug

#241 Fix Alert View Model
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertViewModelTest.kt
Labels: clean up

#250 Refactor `userId` parameter in `AlertViewModel`
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertViewModelTest.kt
Labels: clean up

#225 Feat/timer/view model
  app/src/main/java/com/android/periodpals/model/timer/Timer.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerDto.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerManager.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerModel.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserDto.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerDtoTest.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerManagerTest.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
Labels: enhancement

#248 Feat/misc/notifications/simple-interface : Implement push notification simple interface
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/services/PushNotificationsServiceImpl.kt
  app/src/main/res/drawable-hdpi/ic_notification_icon.png
  app/src/main/res/drawable-mdpi/ic_notification_icon.png
  app/src/main/res/drawable-xhdpi/ic_notification_icon.png
  app/src/main/res/drawable-xxhdpi/ic_notification_icon.png
  app/src/main/res/drawable-xxxhdpi/ic_notification_icon.png
  app/src/test/java/com/android/periodpals/services/PushNotificationsServiceImplTest.kt
  gradle/libs.versions.toml
  supabase/.gitignore
  supabase/config.toml
  supabase/functions/push/index.ts
Labels: enhancement
