Repository PeriodPals/periodpals, pull requests merged in 2024-12, with the labels that each got.

#263 Feat/authentication/form-validation : Integrate form validation library into authentication screens
  app/build.gradle.kts
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationViewModel.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#257 Feat/alert/edit alert navigation
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/alert/Alert.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/alert/EditAlert.kt
  app/src/main/java/com/android/periodpals/ui/components/AlertComponents.kt
  app/src/main/java/com/android/periodpals/ui/navigation/NavigationActions.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertTests.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/EditAlertScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/navigation/NavigationActionsTest.kt
Labels: enhancement

#277 Feat/alert/location filtering
  app/src/main/java/com/android/periodpals/model/alert/Alert.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertDto.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertModel.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/main/java/com/android/periodpals/model/location/LocationGIS.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertViewModelTest.kt
  app/src/test/java/com/android/periodpals/model/location/LocationGISDataClassTest.kt
Labels: enhancement

#270 Feat/timer/integrate vm
  app/build.gradle.kts
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerManager.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/resources/Color.kt
  app/src/main/java/com/android/periodpals/ui/timer/TimerScreen.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerManagerTest.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#282 Feat/misc/notifications/integrate-user-vm : Integrate profile VM to notification interface
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/user/User.kt
  app/src/main/java/com/android/periodpals/model/user/UserDto.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/services/PushNotificationsServiceImpl.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/test/java/com/android/periodpals/model/user/UserModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/periodpals/services/PushNotificationsServiceImplTest.kt
Labels: enhancement

#274 Integrate alert to maps and some other spicy stuff
  .github/workflows/ci.yml
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/services/GPSServiceImpl.kt
  app/src/main/java/com/android/periodpals/ui/map/Map.kt
  app/src/main/res/drawable/alert_marker.xml
  app/src/main/res/drawable/location.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/com/android/periodpals/services/GPSServiceImplTest.kt
  app/src/test/java/com/android/periodpals/ui/map/MapScreenTest.kt
  secrets.defaults.properties
Labels: enhancement, clean up

#290 Feat/alert/alert lists location filter
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/components/AlertComponents.kt
  app/src/test/java/com/android/periodpals/model/alert/AlertViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
Labels: enhancement

#302 Feat/authentication/back to sign in
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/main/java/com/android/periodpals/ui/components/AuthenticationComponents.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignUpTest.kt
Labels: enhancement

#294 Feat/misc/notifications/nearby-users-only : Push notifications for new alerts only to nearby users
  app/src/androidTest/java/com/android/periodpals/services/GPSServiceImplInstrumentedTest.kt
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/location/LocationGIS.kt
  app/src/main/java/com/android/periodpals/model/user/User.kt
  app/src/main/java/com/android/periodpals/model/user/UserDto.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/services/GPSServiceImpl.kt
  app/src/test/java/com/android/periodpals/model/location/LocationGISDataClassTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserDtoTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/periodpals/services/GPSServiceImplTest.kt
  supabase/functions/push_new_alert/index.ts
  supabase/tests/push_new_alert.test.ts
Labels: enhancement

#296 Feat/timer/update instructions
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/timer/Timer.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerDto.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerManager.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerModel.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
  app/src/main/java/com/android/periodpals/ui/timer/TimerScreen.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerDtoTest.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
Labels: enhancement

#304 Feat/timer/notifications/timer-edge-function : Push notifications for timer
  supabase/functions/push_timer/index.ts
  supabase/tests/push_timer.test.ts
Labels: enhancement

#295 Feat/authentication/auth persistence
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationViewModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserAuthenticationState.kt
  app/src/test/java/com/android/periodpals/MainActivityTest.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationViewModelTest.kt
Labels: enhancement

#313 fix/alert/location-input-length : Fix alert location input length
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/test/java/com/android/periodpals/ui/alert/CreateAlertScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/EditAlertScreenTest.kt
Labels: bug

#321 feat/authentication/delete-users : Delete user from `auth.users` upon delete from `public.users`
  supabase/functions/delete_auth_users/index.ts
Labels: bug, enhancement

#309 Feat/chat/client setup
  app/build.gradle.kts
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/chat/ChatViewModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/services/JwtTokenService.kt
  app/src/main/java/com/android/periodpals/ui/chat/Chat.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/main/java/com/android/periodpals/ui/timer/TimerScreen.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationViewModelTest.kt
  app/src/test/java/com/android/periodpals/model/chat/ChatViewModelTest.kt
  app/src/test/java/com/android/periodpals/services/JwtTokenServiceTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  gradle/libs.versions.toml
  secrets.defaults.properties
Labels: enhancement

#315 Feat/profile/age verification : Age verification in CreateProfile and EditProfile screens
  app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/components/ProfileComponents.kt
  app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/EditProfileTest.kt
Labels: enhancement

#331 Fix/timer/extract strings
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/timer/TimerScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
Labels: clean up

#339 Feat/alert/fetch profile picture of other users
  app/src/androidTest/java/com/android/periodpals/services/GPSServiceImplInstrumentedTest.kt
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/user/UserModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt
  app/src/main/java/com/android/periodpals/services/GPSServiceImpl.kt
  app/src/main/java/com/android/periodpals/services/PushNotificationsServiceImpl.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/test/java/com/android/periodpals/model/user/UserModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/periodpals/services/GPSServiceImplTest.kt
  app/src/test/java/com/android/periodpals/services/PushNotificationsServiceImplTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
Labels: enhancement

#337 Fix/misc/profile settings extract strings
  app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/main/java/com/android/periodpals/ui/settings/SettingsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/EditProfileTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/settings/SettingsScreenTest.kt
Labels: clean up

#340 Fix/alert/extract string
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/main/java/com/android/periodpals/ui/alert/EditAlert.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/CreateAlertScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/EditAlertScreenTest.kt
Labels: clean up

#335 Fix/misc/auth map extract strings
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
  app/src/main/java/com/android/periodpals/ui/map/Map.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/ui/authentication/SignInTest.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignUpTest.kt
  app/src/test/java/com/android/periodpals/ui/map/MapScreenTest.kt
Labels: clean up

#348 Feat/settings/clean up settings screen notifs and theme delete text and add preferred distance option
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/settings/SettingsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/ui/settings/SettingsScreenTest.kt
Labels: bug, clean up

#350 Feat/geolocation/secure-location-handling : Secure location handling
  app/src/androidTest/java/com/android/periodpals/services/GPSServiceImplInstrumentedTest.kt
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/location/UserLocationDto.kt
  app/src/main/java/com/android/periodpals/model/location/UserLocationModel.kt
  app/src/main/java/com/android/periodpals/model/location/UserLocationModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/location/UserLocationViewModel.kt
  app/src/main/java/com/android/periodpals/model/user/User.kt
  app/src/main/java/com/android/periodpals/model/user/UserDto.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/services/GPSServiceImpl.kt
  app/src/test/java/com/android/periodpals/model/location/UserLocationDtoTest.kt
  app/src/test/java/com/android/periodpals/model/location/UserLocationModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/location/UserLocationViewModelTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserDtoTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/periodpals/services/GPSServiceImplTest.kt
  supabase/functions/push_new_alert/index.ts
Labels: enhancement

#349 Add connectivity banner to the bottom navigation menu
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/services/NetworkChangeListener.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/main/java/com/android/periodpals/ui/map/Map.kt
  app/src/main/java/com/android/periodpals/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
  app/src/main/java/com/android/periodpals/ui/timer/TimerScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/services/NetworkChangeListenerTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/CreateAlertScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/map/MapScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/navigation/BottomNavigationMenuTest.kt
  app/src/test/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
  app/src/test/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
Labels: enhancement

#359 feat/arch-diagram: Update architecture diagram
  architecture_diagram.excalidraw
Labels: enhancement

#303 Add alerts UI to the map
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/components/AlertComponents.kt
  app/src/main/java/com/android/periodpals/ui/components/MapComponents.kt
  app/src/main/java/com/android/periodpals/ui/map/Map.kt
  app/src/main/res/drawable/marker_blue.xml
  app/src/main/res/drawable/marker_red.xml
  app/src/test/java/com/android/periodpals/ui/map/MapComponentsTest.kt
  app/src/test/java/com/android/periodpals/ui/map/MapScreenTest.kt
Labels: enhancement

#360 Fix/authentication/remove google auth
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModel.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/authentication/AuthenticationViewModel.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationModelSupabaseTest.kt
  app/src/test/java/com/android/periodpals/model/authentication/AuthenticationViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/authentication/SignInTest.kt
Labels: clean up

#327 Test/e2e/adapt existing tests
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndProfile.kt
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndSignIn.kt
  app/src/androidTest/java/com/android/periodpals/endtoend/EndToEndSignUp.kt
Labels: bug, enhancement

#342 Feat/alert/alert lists UI improvements
  app/src/main/java/com/android/periodpals/MainActivity.kt
  app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserModel.kt
  app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
  app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt
  app/src/main/java/com/android/periodpals/resources/C.kt
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/periodpals/model/alert/AlertViewModelTest.kt
  app/src/test/java/com/android/periodpals/ui/alert/AlertListsScreenTest.kt
Labels: bug, enhancement

#366 chore/remove-annoying-toasts : Remove useless toasts
  app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
  app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
  app/src/main/java/com/android/periodpals/ui/map/Map.kt
  app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
Labels: clean up
